### PR TITLE
My_Debtors_Backend

### PR DESCRIPTION
**Pull request by Mukumbuta**
### Summary:
- Set up `Django`project
- Set up user `authentication` app
- Set up base files for the main `My_Debtors_API` app 
- Set up JWT authentication
- Added `Register`user and `Login`functionality
- Added project dependency tree to requirements.txt file

### CODE REVIEW

**Review by chimezdev — COMMENTED** [review]
All good well done my oga. Are we going to be using sqlite?

**Comment by Mukumbuta** [comment]
Hi @chimezdev 
Thank you for the code review.
Kindly mark this PR as approved in your review

**Comment by Mukumbuta** [comment]
Only for development. We will migrate to PostgreSQL in production

**Comment by chimezdev** [comment]
Thank you

**Review by TeamOpossum22 — APPROVED** [review]

**Pull request merged**
